import org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("rasoirbot.kotlin-application-conventions")
}

dependencies {
    val kotlinxCoroutinesVersion = "1.6.4"
    implementation("com.discord4j:discord4j-core:3.2.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxCoroutinesVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:$kotlinxCoroutinesVersion")
    implementation("io.github.microutils:kotlin-logging-jvm:2.1.23")
    runtimeOnly("ch.qos.logback:logback-classic:1.2.11")
}

application {
    // Define the main class for the application.
    mainClass.set("io.github.rasoirdoc.rasoirbot.launcher.BotLauncherKt")
}

val compileOptions: KotlinJvmOptions.() -> Unit = {
    languageVersion = "1.6"
    jvmTarget = "17"
}

val compileKotlin: KotlinCompile by tasks
val compileTestKotlin: KotlinCompile by tasks

compileKotlin.kotlinOptions(compileOptions)
compileTestKotlin.kotlinOptions(compileOptions)
