/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rasoirdoc.rasoirbot.launcher

import discord4j.core.DiscordClient
import discord4j.core.event.domain.message.MessageCreateEvent
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.reactive.asFlow
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.reactor.mono

fun main() {
    val token = System.getenv("DISCORD_BOT_TOKEN") ?: throw IllegalArgumentException("Please set the \"DISCORD_BOT_TOKEN\" environment variable.")
    val client = DiscordClient.create(token)

    client.withGateway { c ->
        mono {
            c.on(MessageCreateEvent::class.java)
                .asFlow()
                .onEach {
                    val message = it.message
                    if (message.content == "!ping") {
                        val channel = message.channel.awaitSingle()
                        channel.createMessage("Pong!").awaitSingle()
                    }
                }
                .launchIn(this)
        }
    }
        .block()
}
